  Activating project at `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-LL/dyn-LL-1000-9/pidc_env`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-LL/dyn-LL-1000-9/pidc_env/Project.toml`
  No Changes to `/data/gpfs/projects/punim0638/stephenz/locaTE-paper/data/simulated/Synthetic_1000/dyn-LL/dyn-LL-1000-9/pidc_env/Manifest.toml`
Getting nodes...
Inferring network...
cat: write error: Broken pipe
2023-10-04 23:42:23.833975
2023-10-04 23:42:26.770148
2023-10-04 23:42:29.988760

real	0m6.953s
user	0m0.006s
sys	0m0.011s
cat: write error: Broken pipe
2023-10-04 23:42:40.943636
2023-10-04 23:42:43.532786
2023-10-04 23:42:46.354070

real	0m6.162s
user	0m0.010s
sys	0m0.007s
cat: write error: Broken pipe
2023-10-04 23:42:57.297400
2023-10-04 23:42:59.749015
2023-10-04 23:43:02.364866

real	0m5.826s
user	0m0.009s
sys	0m0.007s
cat: write error: Broken pipe
2023-10-04 23:43:13.304739
2023-10-04 23:43:15.871143
2023-10-04 23:43:18.524749

real	0m5.968s
user	0m0.009s
sys	0m0.008s
cat: write error: Broken pipe
2023-10-04 23:43:29.534887
2023-10-04 23:43:32.494704
2023-10-04 23:43:35.531384

real	0m6.809s
user	0m0.011s
sys	0m0.005s
cat: write error: Broken pipe
2023-10-04 23:43:46.558214
2023-10-04 23:43:51.682783
2023-10-04 23:43:56.967818

real	0m11.246s
user	0m0.007s
sys	0m0.009s
cat: write error: Broken pipe
2023-10-04 23:44:08.080458
2023-10-04 23:44:13.742277
2023-10-04 23:44:17.837582

real	0m10.642s
user	0m0.011s
sys	0m0.006s
cat: write error: Broken pipe
2023-10-04 23:44:28.808366
2023-10-04 23:44:29.931054
2023-10-04 23:44:31.127949

real	0m3.100s
user	0m0.007s
sys	0m0.010s
mkdir: cannot create directory ‘SCODE_D_2’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_4’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_6’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
mkdir: cannot create directory ‘SCODE_D_8’: File exists
┌ Warning: Assignment to `WZ` in soft scope is ambiguous because a global variable by the same name exists: `WZ` will be treated as a new local. Disambiguate by using `local WZ` to suppress this warning or `global WZ` to assign to the existing global variable.
└ @ ~/stephenz/locaTE-paper/tools/SCODE/SCODE.jl:69
a
sh: line 1: matlab: command not found
sh: line 1: matlab: command not found
/data/gpfs/projects/punim0638/stephenz/envs/py39/lib/python3.9/site-packages/Scribe-0.0.0-py3.9.egg/Scribe/causal_network.py:18: UserWarning:  WARNING: No expression data argument given. if you intend to load the data from a file, call the method 'read_expression_file'.
  if expression==None: warnings.warn(" WARNING: No expression data argument given. if you intend to load the data from a file, call the method 'read_expression_file'.")
/data/gpfs/projects/punim0638/stephenz/envs/py39/lib/python3.9/site-packages/Scribe-0.0.0-py3.9.egg/Scribe/causal_network.py:298: FutureWarning: Could not cast to int64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  max_rdi_delay = pd.DataFrame({node_id: [np.nan for i in self.node_ids] for node_id in self.node_ids}, index=self.node_ids,
Tree method: RF
K: sqrt
Number of trees: 1000


running single threaded jobs
Gene 1/18...
Gene 2/18...
Gene 3/18...
Gene 4/18...
Gene 5/18...
Gene 6/18...
Gene 7/18...
Gene 8/18...
Gene 9/18...
Gene 10/18...
Gene 11/18...
Gene 12/18...
Gene 13/18...
Gene 14/18...
Gene 15/18...
Gene 16/18...
Gene 17/18...
Gene 18/18...
Elapsed time: 52.32 seconds
Create causal_model successfully
